from typing import Protocol, runtime_checkable, List

from devhub.models import RegisteredAgent, RegisteredServer


@runtime_checkable
class StorageStrategy(Protocol):
    async def init(self) -> None: ...
    async def close(self) -> None: ...
    async def register(self, server: RegisteredServer) -> None: ...
    async def save(self, server: RegisteredServer) -> None: ...
    async def unregister(self, server_id: str) -> None: ...
    async def get(self, server_id: str) -> RegisteredServer | None: ...
    async def list(self) -> List[RegisteredServer]: ...
    async def register_agent(self, agent: RegisteredAgent) -> None: ...
    async def save_agent(self, agent: RegisteredAgent) -> None: ...
    async def unregister_agent(self, agent_id: str) -> None: ...
    async def get_agent(self, agent_id: str) -> RegisteredAgent | None: ...
    async def list_agents(self) -> List[RegisteredAgent]: ...
